"""The overwrite-safe write path (D-031b; invariant 5).

The one failure the framework must never have is the silent loss of a teacher's
authored work, and it is unrecoverable. `classkit.write` is where that is prevented in
code rather than by prompt, so these tests check the refusal itself — not a rule that
reports it afterwards.
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest

from classkit.cli import main
from classkit.write import has_content, write

TEACHERS_WORK = "---\nid: U01\n---\n\nWritten by the teacher, by hand.\n"


@pytest.fixture
def target(tmp_path: Path) -> Path:
    return tmp_path / "units" / "01-first" / "unit.md"


# -- the refusal -----------------------------------------------------------

def test_writes_a_file_that_does_not_exist(target: Path):
    outcome = write(target, "new content")

    assert outcome.status == "created"
    assert outcome.wrote
    assert target.read_text(encoding="utf-8") == "new content"


def test_refuses_to_replace_existing_content(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    outcome = write(target, "generated by an agent")

    assert outcome.refused
    assert not outcome.wrote
    assert target.read_text(encoding="utf-8") == TEACHERS_WORK


def test_a_refusal_quotes_what_is_there(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    outcome = write(target, "generated by an agent")

    assert "Written by the teacher" in outcome.preview


def test_replaces_only_on_explicit_confirmation(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    outcome = write(target, "approved replacement", overwrite=True)

    assert outcome.status == "replaced"
    assert target.read_text(encoding="utf-8") == "approved replacement"


def test_ignoring_the_outcome_still_cannot_lose_work(target: Path):
    """A caller that never inspects the return value writes nothing — the guarantee
    does not depend on anyone checking."""
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    write(target, "one")
    write(target, "two")

    assert target.read_text(encoding="utf-8") == TEACHERS_WORK


# -- what is deliberately not a refusal ------------------------------------

def test_an_empty_file_holds_nothing_to_lose(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text("   \n\n", encoding="utf-8")

    outcome = write(target, "real content")

    assert outcome.status == "replaced"
    assert target.read_text(encoding="utf-8") == "real content"


def test_writing_identical_content_is_a_no_op(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    outcome = write(target, TEACHERS_WORK)

    assert outcome.status == "unchanged"
    assert not outcome.refused


def test_a_directory_in_the_way_is_refused_not_replaced(tmp_path: Path):
    directory = tmp_path / "unit.md"
    directory.mkdir()

    assert write(directory, "content").refused
    assert directory.is_dir()


def test_dry_run_reports_without_writing(target: Path):
    outcome = write(target, "content", dry_run=True)

    assert outcome.status == "created"
    assert not target.exists()


def test_has_content(tmp_path: Path):
    missing = tmp_path / "missing.md"
    blank = tmp_path / "blank.md"
    blank.write_text("\n \t\n", encoding="utf-8")
    real = tmp_path / "real.md"
    real.write_text("x", encoding="utf-8")

    assert not has_content(missing)
    assert not has_content(blank)
    assert has_content(real)


# -- the agent-facing surface ----------------------------------------------

def test_cli_write_refuses_with_its_own_exit_code(target: Path, monkeypatch, capsys):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")
    monkeypatch.setattr("sys.stdin", io.StringIO("generated by an agent"))

    assert main(["write", str(target)]) == 3
    assert target.read_text(encoding="utf-8") == TEACHERS_WORK
    assert "refused" in capsys.readouterr().err


def test_cli_write_creates_from_stdin(target: Path, monkeypatch):
    monkeypatch.setattr("sys.stdin", io.StringIO("from an agent"))

    assert main(["write", str(target)]) == 0
    assert target.read_text(encoding="utf-8") == "from an agent"


def test_cli_write_overwrite_flag_is_the_confirmation(target: Path, monkeypatch):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")
    monkeypatch.setattr("sys.stdin", io.StringIO("approved replacement"))

    assert main(["write", str(target), "--overwrite"]) == 0
    assert target.read_text(encoding="utf-8") == "approved replacement"


# -- append mode (D-038): the course log's way in, through the same path -----------

from classkit.write import APPENDED, append as append_to


def test_append_adds_to_the_end_and_never_rewrites(tmp_path):
    target = tmp_path / "LOG.md"
    target.write_text("# Log\n\nfirst entry\n", encoding="utf-8")
    outcome = append_to(target, "second entry\n")
    assert outcome.status == APPENDED and outcome.wrote
    assert target.read_text(encoding="utf-8") == "# Log\n\nfirst entry\nsecond entry\n"


def test_append_creates_a_missing_file_through_write(tmp_path):
    target = tmp_path / "new.md"
    assert append_to(target, "hello\n").status == "created"
    assert target.read_text(encoding="utf-8") == "hello\n"


def test_append_dry_run_writes_nothing(tmp_path):
    target = tmp_path / "LOG.md"
    target.write_text("keep\n", encoding="utf-8")
    assert append_to(target, "more\n", dry_run=True).status == APPENDED
    assert target.read_text(encoding="utf-8") == "keep\n"


def test_append_refuses_a_directory(tmp_path):
    assert append_to(tmp_path, "x").refused


def test_cli_rejects_append_with_overwrite(tmp_path, capsys):
    from classkit.cli import main
    target = tmp_path / "f.md"
    target.write_text("keep\n", encoding="utf-8")
    assert main(["write", str(target), "--append", "--overwrite", "--from", str(target)]) == 2
    assert target.read_text(encoding="utf-8") == "keep\n"


# -- remove (D-041): the one deletion, guarded like a replacement -------------------

from classkit.write import REMOVED, content_hash, diff, remove


def test_remove_deletes_only_what_the_caller_wrote(tmp_path):
    target = tmp_path / "full.md"
    target.write_text("written by ingest\n", encoding="utf-8")
    outcome = remove(target, content_hash(b"written by ingest\n"))
    assert outcome.status == REMOVED and not target.exists()


def test_remove_refuses_a_changed_file(tmp_path):
    target = tmp_path / "full.md"
    target.write_text("written by ingest\nand fixed by the teacher\n", encoding="utf-8")
    outcome = remove(target, content_hash(b"written by ingest\n"))
    assert outcome.refused
    assert target.read_text(encoding="utf-8").endswith("fixed by the teacher\n")


def test_remove_of_a_missing_file_is_a_no_op(tmp_path):
    assert remove(tmp_path / "gone.md", content_hash(b"")).status == "unchanged"


def test_remove_has_no_command_line_verb():
    """Nothing a teacher runs deletes files (spec §8.6)."""
    with pytest.raises(SystemExit):
        main(["remove", "x"])


# -- permissions (D-041) ----------------------------------------------------------------

def test_replacing_a_file_keeps_its_permissions(target: Path):
    import os
    import stat

    target.parent.mkdir(parents=True)
    target.write_text("old\n", encoding="utf-8")
    os.chmod(target, 0o640)
    write(target, "new\n", overwrite=True)
    assert stat.S_IMODE(target.stat().st_mode) == 0o640


def test_a_new_file_gets_the_umask_default_not_0600(target: Path):
    import os
    import stat

    previous = os.umask(0o022)
    try:
        write(target, "new\n")
    finally:
        os.umask(previous)
    assert stat.S_IMODE(target.stat().st_mode) == 0o644


# -- --diff (D-040): show a partial change before making it ----------------------------

def test_diff_shows_exactly_what_overwrite_would_change_and_writes_nothing(tmp_path, monkeypatch, capsys):
    target = tmp_path / "course.yaml"
    target.write_text("code: T-1\n# the teacher's comment\nunits: 13\n", encoding="utf-8")
    monkeypatch.setattr("sys.stdin", io.StringIO("code: T-1\n# the teacher's comment\nunits: 12\n"))

    assert main(["write", str(target), "--diff"]) == 0

    out = capsys.readouterr().out
    assert "-units: 13" in out and "+units: 12" in out
    assert "the teacher's comment" in out and "-# the teacher's comment" not in out
    assert target.read_text(encoding="utf-8").endswith("units: 13\n")


def test_diff_of_identical_content_says_unchanged(tmp_path, monkeypatch, capsys):
    target = tmp_path / "f.md"
    target.write_text("same\n", encoding="utf-8")
    monkeypatch.setattr("sys.stdin", io.StringIO("same\n"))
    assert main(["write", str(target), "--diff"]) == 0
    assert "unchanged" in capsys.readouterr().out
    assert diff(target, "same\n") == ""


def test_diff_of_a_new_file_shows_every_line_added(tmp_path):
    out = diff(tmp_path / "new.md", "one\ntwo\n")
    assert "+one" in out and "+two" in out and not (tmp_path / "new.md").exists()
