"""The overwrite-safe write path (D-031b; invariant 5).

The one failure the framework must never have is the silent loss of a teacher's
authored work, and it is unrecoverable. `classkit.write` is where that is prevented in
code rather than by prompt, so these tests check the refusal itself — not a rule that
reports it afterwards.
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest

from classkit.cli import main
from classkit.write import has_content, write

TEACHERS_WORK = "---\nid: U01\n---\n\nWritten by the teacher, by hand.\n"


@pytest.fixture
def target(tmp_path: Path) -> Path:
    return tmp_path / "units" / "01-first" / "unit.md"


# -- the refusal -----------------------------------------------------------

def test_writes_a_file_that_does_not_exist(target: Path):
    outcome = write(target, "new content")

    assert outcome.status == "created"
    assert outcome.wrote
    assert target.read_text(encoding="utf-8") == "new content"


def test_refuses_to_replace_existing_content(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    outcome = write(target, "generated by an agent")

    assert outcome.refused
    assert not outcome.wrote
    assert target.read_text(encoding="utf-8") == TEACHERS_WORK


def test_a_refusal_quotes_what_is_there(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    outcome = write(target, "generated by an agent")

    assert "Written by the teacher" in outcome.preview


def test_replaces_only_on_explicit_confirmation(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    outcome = write(target, "approved replacement", overwrite=True)

    assert outcome.status == "replaced"
    assert target.read_text(encoding="utf-8") == "approved replacement"


def test_ignoring_the_outcome_still_cannot_lose_work(target: Path):
    """A caller that never inspects the return value writes nothing — the guarantee
    does not depend on anyone checking."""
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    write(target, "one")
    write(target, "two")

    assert target.read_text(encoding="utf-8") == TEACHERS_WORK


# -- what is deliberately not a refusal ------------------------------------

def test_an_empty_file_holds_nothing_to_lose(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text("   \n\n", encoding="utf-8")

    outcome = write(target, "real content")

    assert outcome.status == "replaced"
    assert target.read_text(encoding="utf-8") == "real content"


def test_writing_identical_content_is_a_no_op(target: Path):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")

    outcome = write(target, TEACHERS_WORK)

    assert outcome.status == "unchanged"
    assert not outcome.refused


def test_a_directory_in_the_way_is_refused_not_replaced(tmp_path: Path):
    directory = tmp_path / "unit.md"
    directory.mkdir()

    assert write(directory, "content").refused
    assert directory.is_dir()


def test_dry_run_reports_without_writing(target: Path):
    outcome = write(target, "content", dry_run=True)

    assert outcome.status == "created"
    assert not target.exists()


def test_has_content(tmp_path: Path):
    missing = tmp_path / "missing.md"
    blank = tmp_path / "blank.md"
    blank.write_text("\n \t\n", encoding="utf-8")
    real = tmp_path / "real.md"
    real.write_text("x", encoding="utf-8")

    assert not has_content(missing)
    assert not has_content(blank)
    assert has_content(real)


# -- the agent-facing surface ----------------------------------------------

def test_cli_write_refuses_with_its_own_exit_code(target: Path, monkeypatch, capsys):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")
    monkeypatch.setattr("sys.stdin", io.StringIO("generated by an agent"))

    assert main(["write", str(target)]) == 3
    assert target.read_text(encoding="utf-8") == TEACHERS_WORK
    assert "refused" in capsys.readouterr().err


def test_cli_write_creates_from_stdin(target: Path, monkeypatch):
    monkeypatch.setattr("sys.stdin", io.StringIO("from an agent"))

    assert main(["write", str(target)]) == 0
    assert target.read_text(encoding="utf-8") == "from an agent"


def test_cli_write_overwrite_flag_is_the_confirmation(target: Path, monkeypatch):
    target.parent.mkdir(parents=True)
    target.write_text(TEACHERS_WORK, encoding="utf-8")
    monkeypatch.setattr("sys.stdin", io.StringIO("approved replacement"))

    assert main(["write", str(target), "--overwrite"]) == 0
    assert target.read_text(encoding="utf-8") == "approved replacement"


# -- append mode (D-038): the course log's way in, through the same path -----------

from classkit.write import APPENDED, append as append_to


def test_append_adds_to_the_end_and_never_rewrites(tmp_path):
    target = tmp_path / "LOG.md"
    target.write_text("# Log\n\nfirst entry\n", encoding="utf-8")
    outcome = append_to(target, "second entry\n")
    assert outcome.status == APPENDED and outcome.wrote
    assert target.read_text(encoding="utf-8") == "# Log\n\nfirst entry\nsecond entry\n"


def test_append_creates_a_missing_file_through_write(tmp_path):
    target = tmp_path / "new.md"
    assert append_to(target, "hello\n").status == "created"
    assert target.read_text(encoding="utf-8") == "hello\n"


def test_append_dry_run_writes_nothing(tmp_path):
    target = tmp_path / "LOG.md"
    target.write_text("keep\n", encoding="utf-8")
    assert append_to(target, "more\n", dry_run=True).status == APPENDED
    assert target.read_text(encoding="utf-8") == "keep\n"


def test_append_refuses_a_directory(tmp_path):
    assert append_to(tmp_path, "x").refused


def test_cli_rejects_append_with_overwrite(tmp_path, capsys):
    from classkit.cli import main
    target = tmp_path / "f.md"
    target.write_text("keep\n", encoding="utf-8")
    assert main(["write", str(target), "--append", "--overwrite", "--from", str(target)]) == 2
    assert target.read_text(encoding="utf-8") == "keep\n"
